name: golf_live_scoring
description: "Golf live scoring project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  auto_route: ^10.0.0
  bloc: ^9.0.0
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: GolfLocalizations
  main_locale: en
  arb_dir: assets/l10n
  output_dir: lib/ui/l10n